### ISSUE TITLE
Interceptor support?

### ISSUE THREAD

**Issue by ariefsn** [unjs/ohmyfetch#19]
Hi,
is this have interceptors?

Thanks,

**Comment by ushironoko** [comment]
In Nuxt3, it is no longer possible to pass arbitrary fetches to useFetch. This will be an obstacle to migration for users who used to use @nuxtjs/composition-api's useFetch in combination with axios.

It would be nice if something like the axios interceptor could be implemented in ohmyfetch as well.

**Comment by danielroe** [comment]
@ushironoko The version that allows you to pass arbitrary fetches is called `useAsyncData`.

**Comment by pi0** [comment]
Just added a basic set of interceptors. [Docs](https://github.com/unjs/ohmyfetch#%EF%B8%8F-interceptors). ideas more than welcome to improve.

**Comment by ushironoko** [comment]
Looks like a very flexible API. Thanks!

**Comment by engenes** [comment]
> Так же добавлен базовый набор перехватчиков. [Документы](https://github.com/unjs/ohmyfetch#%EF%B8%8F-interceptors) . идеи более чем приветствуются для улучшения.

How can I catch the error and return a success response?

I want to intercept "not found error".
I make this:

**Call function in component**

```
const fetchOnClick = async () => {
 const data = await $fetch('bad_url', {
   onResponseError(ctx) {
     if (ctx.response.status === 404) {
       console.warn('Not found');

       return {
         status: 'error',
         error: {
           message: 'not found',
         },
       };
     }
   },
 });

 console.log(data);
};
```
After response I see `Not found`, but `data` does not appear in log
That is, with such an error, I still want to get the correct message and clear the error.
So that only data that does not pass the condition enters the error
